// <auto-generated />
using System;
using Forestry.Flo.Services.ConditionsBuilder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forestry.Flo.Services.ConditionsBuilder.Migrations
{
    [DbContext(typeof(ConditionsBuilderContext))]
    [Migration("20221207164230_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Conditions")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forestry.Flo.Services.ConditionsBuilder.Entities.FellingLicenceCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AppliesToSubmittedCompartmentIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionsText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FellingLicenceCondition", "Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
