{{- $ingress := .Values.ingressRoute -}}
{{- if $ingress.app.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "external-web-app.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.ingressRoute.app.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "external-web-app.labels" . | nindent 4 }}
    {{- with .Values.ingressRoute.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
     {{- with .Values.ingressRoute.app.entryPoints }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  tls:
    {{- if .Values.ingressRoute.app.existingSecretName }}
    secretName: {{ .Values.ingressRoute.app.certificate.existingSecretName }}
    {{- else }}
    secretName: {{ include "external-web-app.fullname" . }}-cert
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressRoute.app.hostname }}`)
      middlewares:
       - name: external-csp-header
      services:
      - name: {{ include "external-web-app.fullname" . }}
        port: http
        scheme: http
{{- end }}