// <auto-generated />
using System;
using Forestry.Flo.Services.PropertyProfiles;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forestry.Flo.Services.PropertyProfiles.Migrations
{
    [DbContext(typeof(PropertyProfilesContext))]
    [Migration("20220823113346_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PropertyProfiles")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.UserAccount.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("ContactMobileTelephone")
                        .HasColumnType("text");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateAcceptedPrivacyPolicy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAcceptedTermsAndConditions")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IdentityProviderId")
                        .HasColumnType("text");

                    b.Property<Guid?>("InviteToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InviteTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("PreferredContactMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WoodlandOwnerId");

                    b.ToTable("UserAccount", "Applicants", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrganisation")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WoodlandOwner", "Applicants", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.Compartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CompartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("GISData")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubCompartmentName")
                        .HasColumnType("text");

                    b.Property<double?>("TotalHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("WoodlandName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyProfileId");

                    b.HasIndex("CompartmentNumber", "PropertyProfileId")
                        .IsUnique()
                        .HasFilter("\"SubCompartmentName\" IS NULL");

                    b.HasIndex("CompartmentNumber", "SubCompartmentName", "PropertyProfileId")
                        .IsUnique();

                    b.ToTable("Compartment", "PropertyProfiles");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("HasWoodlandManagementPlan")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsWoodlandCertificationScheme")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NearestTown")
                        .HasColumnType("text");

                    b.Property<string>("OSGridReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandCertificationSchemeReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandManagementPlanReference")
                        .HasColumnType("text");

                    b.Property<Guid>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WoodlandOwnerId");

                    b.HasIndex("Name", "WoodlandOwnerId")
                        .IsUnique();

                    b.ToTable("PropertyProfile", "PropertyProfiles");
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.UserAccount.UserAccount", b =>
                {
                    b.HasOne("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", "WoodlandOwner")
                        .WithMany()
                        .HasForeignKey("WoodlandOwnerId");

                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("WoodlandOwner");
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", b =>
                {
                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<Guid>("WoodlandOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("WoodlandOwnerId");

                            b1.ToTable("WoodlandOwner", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("WoodlandOwnerId");
                        });

                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "OrganisationAddress", b1 =>
                        {
                            b1.Property<Guid>("WoodlandOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("WoodlandOwnerId");

                            b1.ToTable("WoodlandOwner", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("WoodlandOwnerId");
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("OrganisationAddress");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.Compartment", b =>
                {
                    b.HasOne("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", "PropertyProfile")
                        .WithMany("Compartments")
                        .HasForeignKey("PropertyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyProfile");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", b =>
                {
                    b.HasOne("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", null)
                        .WithMany()
                        .HasForeignKey("WoodlandOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", b =>
                {
                    b.Navigation("Compartments");
                });
#pragma warning restore 612, 618
        }
    }
}
