{{- if .Values.helperPod.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.helperPod.name }}
  namespace: {{ .Values.job.namespace }}
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: {{ .Values.helperPod.image }}
      command: ["sh", "-c", "sleep {{ .Values.helperPod.ttlSeconds }}"]
      volumeMounts:
        - name: results
          mountPath: /results
  volumes:
    - name: results
      persistentVolumeClaim:
        claimName: {{ .Values.results.pvc.name }}
{{- end }}
