// <auto-generated />
using System;
using Forestry.Flo.Services.FellingLicenceApplications;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forestry.Flo.Services.FellingLicenceApplications.Migrations
{
    [DbContext(typeof(FellingLicenceApplicationsContext))]
    [Migration("20221111175546_External-Link-Access-Code-Guid")]
    partial class ExternalLinkAccessCodeGuid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FellingLicenceApplications")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("AppRefIdCounter2022");

            modelBuilder.HasSequence("AppRefIdCounter2023");

            modelBuilder.HasSequence("AppRefIdCounter2024");

            modelBuilder.HasSequence("AppRefIdCounter2025");

            modelBuilder.HasSequence("AppRefIdCounter2026");

            modelBuilder.HasSequence("AppRefIdCounter2027");

            modelBuilder.HasSequence("AppRefIdCounter2028");

            modelBuilder.HasSequence("AppRefIdCounter2029");

            modelBuilder.HasSequence("AppRefIdCounter2030");

            modelBuilder.HasSequence("AppRefIdCounter2031");

            modelBuilder.HasSequence("AppRefIdCounter2032");

            modelBuilder.HasSequence("AppRefIdCounter2033");

            modelBuilder.HasSequence("AppRefIdCounter2034");

            modelBuilder.HasSequence("AppRefIdCounter2035");

            modelBuilder.HasSequence("AppRefIdCounter2036");

            modelBuilder.HasSequence("AppRefIdCounter2037");

            modelBuilder.HasSequence("AppRefIdCounter2038");

            modelBuilder.HasSequence("AppRefIdCounter2039");

            modelBuilder.HasSequence("AppRefIdCounter2040");

            modelBuilder.HasSequence("AppRefIdCounter2041");

            modelBuilder.HasSequence("AppRefIdCounter2042");

            modelBuilder.HasSequence("AppRefIdCounter2043");

            modelBuilder.HasSequence("AppRefIdCounter2044");

            modelBuilder.HasSequence("AppRefIdCounter2045");

            modelBuilder.HasSequence("AppRefIdCounter2046");

            modelBuilder.HasSequence("AppRefIdCounter2047");

            modelBuilder.HasSequence("AppRefIdCounter2048");

            modelBuilder.HasSequence("AppRefIdCounter2049");

            modelBuilder.HasSequence("AppRefIdCounter2050");

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.Agent.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text");

                    b.Property<bool>("ShouldAutoApproveThinningApplications")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Agency", "Applicants", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.UserAccount.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactMobileTelephone")
                        .HasColumnType("text");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateAcceptedPrivacyPolicy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAcceptedTermsAndConditions")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IdentityProviderId")
                        .HasColumnType("text");

                    b.Property<Guid?>("InviteToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InviteTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("PreferredContactMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("WoodlandOwnerId");

                    b.ToTable("UserAccount", "Applicants", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrganisation")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WoodlandOwner", "Applicants", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.AssigneeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimestampUnassigned")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("AssigneeHistory", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.CaseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<bool>("VisibleToApplicant")
                        .HasColumnType("boolean");

                    b.Property<bool>("VisibleToConsultee")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("CaseNote", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double>("AreaToBeFelled")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsPartOfTreePreservationOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWithinConservationArea")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmittedFlaPropertyCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreeMarking")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedFlaPropertyCompartmentId")
                        .IsUnique();

                    b.ToTable("ConfirmedFellingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ConfirmedFellingDetailId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedFellingDetailId");

                    b.ToTable("ConfirmedFellingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<double?>("PercentageOfRestockArea")
                        .HasColumnType("double precision");

                    b.Property<double>("RestockingDensity")
                        .HasColumnType("double precision");

                    b.Property<int>("RestockingProposal")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmittedFlaPropertyCompartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedFlaPropertyCompartmentId")
                        .IsUnique();

                    b.ToTable("ConfirmedRestockingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ConfirmedRestockingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedRestockingDetailsId");

                    b.ToTable("ConfirmedRestockingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AttachedById")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachedByType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VisibleToApplicant")
                        .HasColumnType("boolean");

                    b.Property<bool>("VisibleToConsultee")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("Document", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ExternalAccessLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AccessCode")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMultipleUseAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("ExternalAccessLink", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ActualFellingEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualFellingStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicationReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinalActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Measures")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProposedFellingEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProposedFellingStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProposedTiming")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TermsAndConditionsAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationReference")
                        .IsUnique();

                    b.ToTable("FellingLicenceApplication", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplicationStepStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("ApplicationDetailsStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("CompartmentFellingRestockingStatuses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("OperationsStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SelectCompartmentsStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SupportingDocumentationStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TermsAndConditionsStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("FellingLicenceApplicationStepStatus", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProposedFellingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreeMarking")
                        .HasColumnType("text");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProposedFellingDetailsId");

                    b.ToTable("FellingOutcome", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProposedFellingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProposedFellingDetailsId");

                    b.ToTable("FellingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("LinkedPropertyProfile", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double>("AreaToBeFelled")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsPartOfTreePreservationOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWithinConservationArea")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LinkedPropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreeMarking")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedPropertyProfileId");

                    b.ToTable("ProposedFellingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LinkedPropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PercentageOfRestockArea")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PropertyProfileCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<double>("RestockingDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("RestockingProposal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedPropertyProfileId");

                    b.ToTable("ProposedRestockingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.PublicRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int?>("EsriId")
                        .HasColumnType("integer");

                    b.Property<bool>("ExemptFromPublicRegister")
                        .HasColumnType("boolean");

                    b.Property<string>("ExemptionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublicationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RemovedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("PublicRegister", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProposedRestockingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedRestockingDetailsId");

                    b.ToTable("RestockingOutcome", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProposedRestockingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedRestockingDetailsId");

                    b.ToTable("RestockingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("StatusHistory", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CompartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("GISData")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubCompartmentName")
                        .HasColumnType("text");

                    b.Property<Guid>("SubmittedFlaPropertyDetailId")
                        .HasColumnType("uuid");

                    b.Property<double?>("TotalHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("WoodlandName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedFlaPropertyDetailId");

                    b.ToTable("SubmittedFlaPropertyCompartment", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasWoodlandManagementPlan")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsWoodlandCertificationScheme")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NearestTown")
                        .HasColumnType("text");

                    b.Property<string>("OSGridReference")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("WoodlandCertificationSchemeReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandManagementPlanReference")
                        .HasColumnType("text");

                    b.Property<Guid>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("SubmittedFlaPropertyDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("AreProposalsUkfsCompliant")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConditionsToApplicantDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConfirmedFellingAndRestockingComplete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaChecklistDone")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaThresholdExceeded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaTrackerCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsApplicationValid")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsConditional")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LandInformationSearchChecked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Pw14ChecksComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendedLicenceDuration")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SiteVisitArtefactsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SiteVisitNotNeeded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SiteVisitNotesRetrieved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("TpoOrCaDeclared")
                        .HasColumnType("boolean");

                    b.Property<bool>("WoodlandOfficerReviewComplete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("WoodlandOfficerReview", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.Compartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("GISData")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubCompartmentName")
                        .HasColumnType("text");

                    b.Property<double?>("TotalHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("WoodlandName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyProfileId");

                    b.ToTable("Compartment", "FellingLicenceApplications", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasWoodlandManagementPlan")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsWoodlandCertificationScheme")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NearestTown")
                        .HasColumnType("text");

                    b.Property<string>("OSGridReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandCertificationSchemeReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandManagementPlanReference")
                        .HasColumnType("text");

                    b.Property<Guid>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PropertyProfile", "FellingLicenceApplications", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.Agent.Agency", b =>
                {
                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AgencyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("AgencyId");

                            b1.ToTable("Agency", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("AgencyId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.UserAccount.UserAccount", b =>
                {
                    b.HasOne("Forestry.Flo.Services.Applicants.Entities.Agent.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId");

                    b.HasOne("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", "WoodlandOwner")
                        .WithMany()
                        .HasForeignKey("WoodlandOwnerId");

                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Agency");

                    b.Navigation("ContactAddress");

                    b.Navigation("WoodlandOwner");
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", b =>
                {
                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<Guid>("WoodlandOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("WoodlandOwnerId");

                            b1.ToTable("WoodlandOwner", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("WoodlandOwnerId");
                        });

                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "OrganisationAddress", b1 =>
                        {
                            b1.Property<Guid>("WoodlandOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("WoodlandOwnerId");

                            b1.ToTable("WoodlandOwner", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("WoodlandOwnerId");
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("OrganisationAddress");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.AssigneeHistory", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithMany("AssigneeHistories")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.CaseNote", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", null)
                        .WithMany("CaseNotes")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", "SubmittedFlaPropertyCompartment")
                        .WithOne("ConfirmedFellingDetail")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", "SubmittedFlaPropertyCompartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SubmittedFlaPropertyCompartment");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", "ConfirmedFellingDetail")
                        .WithMany("ConfirmedFellingSpecies")
                        .HasForeignKey("ConfirmedFellingDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", "SubmittedFlaPropertyCompartment")
                        .WithOne("ConfirmedRestockingDetail")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", "SubmittedFlaPropertyCompartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SubmittedFlaPropertyCompartment");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", "ConfirmedRestockingDetail")
                        .WithMany("ConfirmedRestockingSpecies")
                        .HasForeignKey("ConfirmedRestockingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedRestockingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.Document", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithMany("Documents")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ExternalAccessLink", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", null)
                        .WithMany("ExternalAccessLinks")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplicationStepStatus", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("FellingLicenceApplicationStepStatus")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplicationStepStatus", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingOutcome", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", "ProposedFellingDetail")
                        .WithMany("FellingOutcomes")
                        .HasForeignKey("ProposedFellingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", "ProposedFellingDetail")
                        .WithMany("FellingSpecies")
                        .HasForeignKey("ProposedFellingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("LinkedPropertyProfile")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", "LinkedPropertyProfile")
                        .WithMany("ProposedFellingDetails")
                        .HasForeignKey("LinkedPropertyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedPropertyProfile");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", "LinkedPropertyProfile")
                        .WithMany("ProposedRestockingDetails")
                        .HasForeignKey("LinkedPropertyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedPropertyProfile");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.PublicRegister", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("PublicRegister")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.PublicRegister", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingOutcome", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", "ProposedRestockingDetail")
                        .WithMany("RestockingOutcomes")
                        .HasForeignKey("ProposedRestockingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedRestockingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", "ProposedRestockingDetail")
                        .WithMany("RestockingSpecies")
                        .HasForeignKey("ProposedRestockingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedRestockingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.StatusHistory", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithMany("StatusHistories")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", "SubmittedFlaPropertyDetail")
                        .WithMany("SubmittedFlaPropertyCompartments")
                        .HasForeignKey("SubmittedFlaPropertyDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedFlaPropertyDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("SubmittedFlaPropertyDetail")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("WoodlandOfficerReview")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.Compartment", b =>
                {
                    b.HasOne("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", "PropertyProfile")
                        .WithMany("Compartments")
                        .HasForeignKey("PropertyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyProfile");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", b =>
                {
                    b.Navigation("ConfirmedFellingSpecies");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", b =>
                {
                    b.Navigation("ConfirmedRestockingSpecies");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", b =>
                {
                    b.Navigation("AssigneeHistories");

                    b.Navigation("CaseNotes");

                    b.Navigation("Documents");

                    b.Navigation("ExternalAccessLinks");

                    b.Navigation("FellingLicenceApplicationStepStatus")
                        .IsRequired();

                    b.Navigation("LinkedPropertyProfile");

                    b.Navigation("PublicRegister");

                    b.Navigation("StatusHistories");

                    b.Navigation("SubmittedFlaPropertyDetail");

                    b.Navigation("WoodlandOfficerReview");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", b =>
                {
                    b.Navigation("ProposedFellingDetails");

                    b.Navigation("ProposedRestockingDetails");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", b =>
                {
                    b.Navigation("FellingOutcomes");

                    b.Navigation("FellingSpecies");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", b =>
                {
                    b.Navigation("RestockingOutcomes");

                    b.Navigation("RestockingSpecies");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", b =>
                {
                    b.Navigation("ConfirmedFellingDetail");

                    b.Navigation("ConfirmedRestockingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", b =>
                {
                    b.Navigation("SubmittedFlaPropertyCompartments");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", b =>
                {
                    b.Navigation("Compartments");
                });
#pragma warning restore 612, 618
        }
    }
}
