// <auto-generated />
using System;
using Forestry.Flo.Services.FellingLicenceApplications;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forestry.Flo.Services.FellingLicenceApplications.Migrations
{
    [DbContext(typeof(FellingLicenceApplicationsContext))]
    [Migration("20250908085315_AddEiaScreeningFlagToWoodlandOfficerReviewEntity")]
    partial class AddEiaScreeningFlagToWoodlandOfficerReviewEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FellingLicenceApplications")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("AppRefIdCounter2022");

            modelBuilder.HasSequence("AppRefIdCounter2023");

            modelBuilder.HasSequence("AppRefIdCounter2024");

            modelBuilder.HasSequence("AppRefIdCounter2025");

            modelBuilder.HasSequence("AppRefIdCounter2026");

            modelBuilder.HasSequence("AppRefIdCounter2027");

            modelBuilder.HasSequence("AppRefIdCounter2028");

            modelBuilder.HasSequence("AppRefIdCounter2029");

            modelBuilder.HasSequence("AppRefIdCounter2030");

            modelBuilder.HasSequence("AppRefIdCounter2031");

            modelBuilder.HasSequence("AppRefIdCounter2032");

            modelBuilder.HasSequence("AppRefIdCounter2033");

            modelBuilder.HasSequence("AppRefIdCounter2034");

            modelBuilder.HasSequence("AppRefIdCounter2035");

            modelBuilder.HasSequence("AppRefIdCounter2036");

            modelBuilder.HasSequence("AppRefIdCounter2037");

            modelBuilder.HasSequence("AppRefIdCounter2038");

            modelBuilder.HasSequence("AppRefIdCounter2039");

            modelBuilder.HasSequence("AppRefIdCounter2040");

            modelBuilder.HasSequence("AppRefIdCounter2041");

            modelBuilder.HasSequence("AppRefIdCounter2042");

            modelBuilder.HasSequence("AppRefIdCounter2043");

            modelBuilder.HasSequence("AppRefIdCounter2044");

            modelBuilder.HasSequence("AppRefIdCounter2045");

            modelBuilder.HasSequence("AppRefIdCounter2046");

            modelBuilder.HasSequence("AppRefIdCounter2047");

            modelBuilder.HasSequence("AppRefIdCounter2048");

            modelBuilder.HasSequence("AppRefIdCounter2049");

            modelBuilder.HasSequence("AppRefIdCounter2050");

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.Agent.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrganisation")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text");

                    b.Property<bool>("ShouldAutoApproveThinningApplications")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Agency", "Applicants", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.UserAccount.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactMobileTelephone")
                        .HasColumnType("text");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateAcceptedPrivacyPolicy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAcceptedTermsAndConditions")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IdentityProviderId")
                        .HasColumnType("text");

                    b.Property<Guid?>("InviteToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InviteTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("PreferredContactMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("WoodlandOwnerId");

                    b.ToTable("UserAccount", "Applicants", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrganisation")
                        .HasColumnType("boolean");

                    b.Property<string>("LandlordFirstName")
                        .HasColumnType("text");

                    b.Property<string>("LandlordLastName")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text");

                    b.Property<int>("TenantType")
                        .HasColumnType("integer");

                    b.Property<int>("WoodlandOwnerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WoodlandOwner", "Applicants", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.AdminOfficerReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("AdminOfficerReviewComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("AgentAuthorityCheckFailureReason")
                        .HasColumnType("text");

                    b.Property<bool?>("AgentAuthorityCheckPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AgentAuthorityFormChecked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CBWChecked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ConstraintsChecked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaChecked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("LarchChecked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MappingCheckFailureReason")
                        .HasColumnType("text");

                    b.Property<bool?>("MappingCheckPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MappingChecked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("AdminOfficerReview", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ApproverReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ApprovedLicenceDuration")
                        .HasColumnType("text");

                    b.Property<bool>("CheckedApplication")
                        .HasColumnType("boolean");

                    b.Property<bool>("CheckedCaseNotes")
                        .HasColumnType("boolean");

                    b.Property<bool>("CheckedDocumentation")
                        .HasColumnType("boolean");

                    b.Property<bool>("CheckedWOReview")
                        .HasColumnType("boolean");

                    b.Property<string>("DurationChangeReason")
                        .HasColumnType("text");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InformedApplicant")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicRegisterExemptionReason")
                        .HasColumnType("text");

                    b.Property<bool?>("PublicRegisterPublish")
                        .HasColumnType("boolean");

                    b.Property<int>("RequestedStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("ApproverReview", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.AssigneeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimestampUnassigned")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("AssigneeHistory", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.CaseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<bool>("VisibleToApplicant")
                        .HasColumnType("boolean");

                    b.Property<bool>("VisibleToConsultee")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("CaseNote", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double>("AreaToBeFelled")
                        .HasColumnType("double precision");

                    b.Property<string>("ConservationAreaReference")
                        .HasColumnType("text");

                    b.Property<double>("EstimatedTotalFellingVolume")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsPartOfTreePreservationOrder")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRestocking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWithinConservationArea")
                        .HasColumnType("boolean");

                    b.Property<string>("NoRestockingReason")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProposedFellingDetailId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmittedFlaPropertyCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreeMarking")
                        .HasColumnType("text");

                    b.Property<string>("TreePreservationOrderReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedFlaPropertyCompartmentId");

                    b.ToTable("ConfirmedFellingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ConfirmedFellingDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedFellingDetailId");

                    b.ToTable("ConfirmedFellingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ConfirmedFellingDetailId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<int?>("PercentNaturalRegeneration")
                        .HasColumnType("integer");

                    b.Property<int?>("PercentOpenSpace")
                        .HasColumnType("integer");

                    b.Property<double?>("PercentageOfRestockArea")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ProposedRestockingDetailId")
                        .HasColumnType("uuid");

                    b.Property<double?>("RestockingDensity")
                        .HasColumnType("double precision");

                    b.Property<int>("RestockingProposal")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmittedFlaPropertyCompartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedFellingDetailId");

                    b.ToTable("ConfirmedRestockingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ConfirmedRestockingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedRestockingDetailsId");

                    b.ToTable("ConfirmedRestockingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConsulteeComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AuthorContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("ConsulteeComment", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AttachedById")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachedByType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VisibleToApplicant")
                        .HasColumnType("boolean");

                    b.Property<bool>("VisibleToConsultee")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("Document", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.EnvironmentalImpactAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("AreAttachedFormsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("EiaTrackerReferenceNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("HasApplicationBeenCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasApplicationBeenSent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasTheEiaFormBeenReceived")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("EnvironmentalImpactAssessment", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.EnvironmentalImpactAssessmentRequestHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("EnvironmentalImpactAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestingUserId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentalImpactAssessmentId");

                    b.ToTable("EnvironmentalImpactAssessmentRequestHistory", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ExternalAccessLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AccessCode")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMultipleUseAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("ExternalAccessLink", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ActualFellingEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualFellingStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdministrativeRegion")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .HasColumnType("text");

                    b.Property<string>("CentrePoint")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CitizensCharterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExternalLisAccessedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinalActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FinalActionDateExtended")
                        .HasColumnType("boolean");

                    b.Property<string>("Measures")
                        .HasColumnType("text");

                    b.Property<bool>("NotRunningExternalLisReport")
                        .HasColumnType("boolean");

                    b.Property<string>("OSGridReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProposedFellingEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProposedFellingStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProposedTiming")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TermsAndConditionsAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("VoluntaryWithdrawalNotificationTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationReference")
                        .IsUnique();

                    b.ToTable("FellingLicenceApplication", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplicationStepStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("ApplicationDetailsStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("CompartmentFellingRestockingStatuses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ConstraintCheckStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EnvironmentalImpactAssessmentStatus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("OperationsStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SelectCompartmentsStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SupportingDocumentationStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TermsAndConditionsStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("FellingLicenceApplicationStepStatus", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProposedFellingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreeMarking")
                        .HasColumnType("text");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProposedFellingDetailsId");

                    b.ToTable("FellingOutcome", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ProposedFellingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedFellingDetailsId");

                    b.ToTable("FellingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LarchCheckDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("ConfirmInspectionLog")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ConfirmLarchOnly")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ConfirmMoratorium")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FlightDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlightObservations")
                        .HasColumnType("text");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecommendSplitApplicationDue")
                        .HasColumnType("integer");

                    b.Property<bool>("Zone1")
                        .HasColumnType("boolean");

                    b.Property<bool>("Zone2")
                        .HasColumnType("boolean");

                    b.Property<bool>("Zone3")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("LarchCheckDetails", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("LinkedPropertyProfile", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double>("AreaToBeFelled")
                        .HasColumnType("double precision");

                    b.Property<string>("ConservationAreaReference")
                        .HasColumnType("text");

                    b.Property<double>("EstimatedTotalFellingVolume")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsPartOfTreePreservationOrder")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRestocking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWithinConservationArea")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LinkedPropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoRestockingReason")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreeMarking")
                        .HasColumnType("text");

                    b.Property<string>("TreePreservationOrderReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedPropertyProfileId", "PropertyProfileCompartmentId", "OperationType")
                        .IsUnique();

                    b.ToTable("ProposedFellingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<double?>("PercentageOfRestockArea")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PropertyProfileCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProposedFellingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<double?>("RestockingDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("RestockingProposal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedFellingDetailsId", "PropertyProfileCompartmentId", "RestockingProposal")
                        .IsUnique();

                    b.ToTable("ProposedRestockingDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.PublicRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ConsultationPublicRegisterExpiryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConsultationPublicRegisterPublicationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConsultationPublicRegisterRemovedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionPublicRegisterExpiryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionPublicRegisterPublicationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionPublicRegisterRemovedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EsriId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("WoodlandOfficerConsultationPublicRegisterExemptionReason")
                        .HasColumnType("text");

                    b.Property<bool>("WoodlandOfficerSetAsExemptFromConsultationPublicRegister")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("PublicRegister", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProposedRestockingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedRestockingDetailsId");

                    b.ToTable("RestockingOutcome", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProposedRestockingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedRestockingDetailsId");

                    b.ToTable("RestockingSpecies", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SiteVisitEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WoodlandOfficerReviewId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WoodlandOfficerReviewId");

                    b.ToTable("SiteVisitEvidence", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId");

                    b.ToTable("StatusHistory", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CompartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ConfirmedTotalHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("GISData")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubCompartmentName")
                        .HasColumnType("text");

                    b.Property<Guid>("SubmittedFlaPropertyDetailId")
                        .HasColumnType("uuid");

                    b.Property<double?>("TotalHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("WoodlandName")
                        .HasColumnType("text");

                    b.Property<bool>("Zone1")
                        .HasColumnType("boolean");

                    b.Property<bool>("Zone2")
                        .HasColumnType("boolean");

                    b.Property<bool>("Zone3")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedFlaPropertyDetailId");

                    b.ToTable("SubmittedFlaPropertyCompartment", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasWoodlandManagementPlan")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsWoodlandCertificationScheme")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOfWood")
                        .HasColumnType("text");

                    b.Property<string>("NearestTown")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("WoodlandCertificationSchemeReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandManagementPlanReference")
                        .HasColumnType("text");

                    b.Property<Guid>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("SubmittedFlaPropertyDetail", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("AreProposalsUkfsCompliant")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ComplianceRecommendationsEnacted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConditionsToApplicantDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConfirmedFellingAndRestockingComplete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaChecklistDone")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaScreeningComplete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaThresholdExceeded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EiaTrackerCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EpsLicenceConsidered")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FellingLicenceApplicationId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("InterestDeclarationCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("InterestDeclared")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsApplicationValid")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsConditional")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LandInformationSearchChecked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LarchCheckComplete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("LocalAuthorityConsulted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MapAccuracyConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Pw14ChecksComplete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RecommendationForDecisionPublicRegister")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendedLicenceDuration")
                        .HasColumnType("text");

                    b.Property<bool?>("SiteVisitArrangementsMade")
                        .HasColumnType("boolean");

                    b.Property<bool>("SiteVisitComplete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SiteVisitNeeded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Stage1HabitatRegulationsAssessmentRequired")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TpoOrCaDeclared")
                        .HasColumnType("boolean");

                    b.Property<bool>("WoodlandOfficerReviewComplete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FellingLicenceApplicationId")
                        .IsUnique();

                    b.ToTable("WoodlandOfficerReview", "FellingLicenceApplications");
                });

            modelBuilder.Entity("Forestry.Flo.Services.InternalUsers.Entities.UserAccount.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<int?>("AccountTypeOther")
                        .HasColumnType("integer");

                    b.Property<bool>("CanApproveApplications")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IdentityProviderId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAccount", "InternalUsers", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.Compartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("GISData")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubCompartmentName")
                        .HasColumnType("text");

                    b.Property<double?>("TotalHectares")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PropertyProfileId");

                    b.ToTable("Compartment", "FellingLicenceApplications", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasWoodlandManagementPlan")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWoodlandCertificationScheme")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOfWood")
                        .HasColumnType("text");

                    b.Property<string>("NearestTown")
                        .HasColumnType("text");

                    b.Property<string>("OSGridReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandCertificationSchemeReference")
                        .HasColumnType("text");

                    b.Property<string>("WoodlandManagementPlanReference")
                        .HasColumnType("text");

                    b.Property<Guid>("WoodlandOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PropertyProfile", "FellingLicenceApplications", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.Agent.Agency", b =>
                {
                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AgencyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("AgencyId");

                            b1.ToTable("Agency", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("AgencyId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.UserAccount.UserAccount", b =>
                {
                    b.HasOne("Forestry.Flo.Services.Applicants.Entities.Agent.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId");

                    b.HasOne("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", "WoodlandOwner")
                        .WithMany()
                        .HasForeignKey("WoodlandOwnerId");

                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Agency");

                    b.Navigation("ContactAddress");

                    b.Navigation("WoodlandOwner");
                });

            modelBuilder.Entity("Forestry.Flo.Services.Applicants.Entities.WoodlandOwner.WoodlandOwner", b =>
                {
                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<Guid>("WoodlandOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("WoodlandOwnerId");

                            b1.ToTable("WoodlandOwner", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("WoodlandOwnerId");
                        });

                    b.OwnsOne("Forestry.Flo.Services.Applicants.Entities.Address", "OrganisationAddress", b1 =>
                        {
                            b1.Property<Guid>("WoodlandOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Line1")
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .HasColumnType("text");

                            b1.Property<string>("Line3")
                                .HasColumnType("text");

                            b1.Property<string>("Line4")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.HasKey("WoodlandOwnerId");

                            b1.ToTable("WoodlandOwner", "Applicants");

                            b1.WithOwner()
                                .HasForeignKey("WoodlandOwnerId");
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("OrganisationAddress");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.AdminOfficerReview", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("AdminOfficerReview")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.AdminOfficerReview", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ApproverReview", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("ApproverReview")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.ApproverReview", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.AssigneeHistory", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithMany("AssigneeHistories")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.CaseNote", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", null)
                        .WithMany("CaseNotes")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", "SubmittedFlaPropertyCompartment")
                        .WithMany("ConfirmedFellingDetails")
                        .HasForeignKey("SubmittedFlaPropertyCompartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedFlaPropertyCompartment");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", "ConfirmedFellingDetail")
                        .WithMany("ConfirmedFellingSpecies")
                        .HasForeignKey("ConfirmedFellingDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", "ConfirmedFellingDetail")
                        .WithMany("ConfirmedRestockingDetails")
                        .HasForeignKey("ConfirmedFellingDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", "ConfirmedRestockingDetail")
                        .WithMany("ConfirmedRestockingSpecies")
                        .HasForeignKey("ConfirmedRestockingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedRestockingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConsulteeComment", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", null)
                        .WithMany("ConsulteeComments")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.Document", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithMany("Documents")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.EnvironmentalImpactAssessment", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("EnvironmentalImpactAssessment")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.EnvironmentalImpactAssessment", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.EnvironmentalImpactAssessmentRequestHistory", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.EnvironmentalImpactAssessment", "EnvironmentalImpactAssessment")
                        .WithMany("EiaRequests")
                        .HasForeignKey("EnvironmentalImpactAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvironmentalImpactAssessment");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ExternalAccessLink", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", null)
                        .WithMany("ExternalAccessLinks")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplicationStepStatus", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("FellingLicenceApplicationStepStatus")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplicationStepStatus", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingOutcome", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", "ProposedFellingDetail")
                        .WithMany("FellingOutcomes")
                        .HasForeignKey("ProposedFellingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", "ProposedFellingDetail")
                        .WithMany("FellingSpecies")
                        .HasForeignKey("ProposedFellingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LarchCheckDetails", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("LarchCheckDetails")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.LarchCheckDetails", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("LinkedPropertyProfile")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", "LinkedPropertyProfile")
                        .WithMany("ProposedFellingDetails")
                        .HasForeignKey("LinkedPropertyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedPropertyProfile");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", "ProposedFellingDetail")
                        .WithMany("ProposedRestockingDetails")
                        .HasForeignKey("ProposedFellingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedFellingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.PublicRegister", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("PublicRegister")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.PublicRegister", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingOutcome", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", "ProposedRestockingDetail")
                        .WithMany("RestockingOutcomes")
                        .HasForeignKey("ProposedRestockingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedRestockingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.RestockingSpecies", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", "ProposedRestockingDetail")
                        .WithMany("RestockingSpecies")
                        .HasForeignKey("ProposedRestockingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedRestockingDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SiteVisitEvidence", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", "WoodlandOfficerReview")
                        .WithMany("SiteVisitEvidences")
                        .HasForeignKey("WoodlandOfficerReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WoodlandOfficerReview");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.StatusHistory", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithMany("StatusHistories")
                        .HasForeignKey("FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", "SubmittedFlaPropertyDetail")
                        .WithMany("SubmittedFlaPropertyCompartments")
                        .HasForeignKey("SubmittedFlaPropertyDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedFlaPropertyDetail");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("SubmittedFlaPropertyDetail")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", b =>
                {
                    b.HasOne("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", "FellingLicenceApplication")
                        .WithOne("WoodlandOfficerReview")
                        .HasForeignKey("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", "FellingLicenceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FellingLicenceApplication");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.Compartment", b =>
                {
                    b.HasOne("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", "PropertyProfile")
                        .WithMany("Compartments")
                        .HasForeignKey("PropertyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyProfile");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedFellingDetail", b =>
                {
                    b.Navigation("ConfirmedFellingSpecies");

                    b.Navigation("ConfirmedRestockingDetails");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ConfirmedRestockingDetail", b =>
                {
                    b.Navigation("ConfirmedRestockingSpecies");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.EnvironmentalImpactAssessment", b =>
                {
                    b.Navigation("EiaRequests");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.FellingLicenceApplication", b =>
                {
                    b.Navigation("AdminOfficerReview");

                    b.Navigation("ApproverReview");

                    b.Navigation("AssigneeHistories");

                    b.Navigation("CaseNotes");

                    b.Navigation("ConsulteeComments");

                    b.Navigation("Documents");

                    b.Navigation("EnvironmentalImpactAssessment");

                    b.Navigation("ExternalAccessLinks");

                    b.Navigation("FellingLicenceApplicationStepStatus")
                        .IsRequired();

                    b.Navigation("LarchCheckDetails");

                    b.Navigation("LinkedPropertyProfile");

                    b.Navigation("PublicRegister");

                    b.Navigation("StatusHistories");

                    b.Navigation("SubmittedFlaPropertyDetail");

                    b.Navigation("WoodlandOfficerReview");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.LinkedPropertyProfile", b =>
                {
                    b.Navigation("ProposedFellingDetails");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedFellingDetail", b =>
                {
                    b.Navigation("FellingOutcomes");

                    b.Navigation("FellingSpecies");

                    b.Navigation("ProposedRestockingDetails");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.ProposedRestockingDetail", b =>
                {
                    b.Navigation("RestockingOutcomes");

                    b.Navigation("RestockingSpecies");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyCompartment", b =>
                {
                    b.Navigation("ConfirmedFellingDetails");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.SubmittedFlaPropertyDetail", b =>
                {
                    b.Navigation("SubmittedFlaPropertyCompartments");
                });

            modelBuilder.Entity("Forestry.Flo.Services.FellingLicenceApplications.Entities.WoodlandOfficerReview", b =>
                {
                    b.Navigation("SiteVisitEvidences");
                });

            modelBuilder.Entity("Forestry.Flo.Services.PropertyProfiles.Entities.PropertyProfile", b =>
                {
                    b.Navigation("Compartments");
                });
#pragma warning restore 612, 618
        }
    }
}
