apiVersion: v2
name: flo
description: A Helm chart FLO
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://twitter.com/QxlvaHealth/photo
sources:
  - https://bitbucket.org/quicksilva/flo-v2/src/master/source/helm/flo/
maintainers:
  - name: Quicksilva
    email: platform@qxlva.com
dependencies:
  - name: postgresql
    version: 12.9.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: global.postgresql.enabled

  - name: external-web-app
    version: ~1.0.0
    repository: oci://fsflo.azurecr.io/helm
    condition: external-web-app.enabled

  - name: internal-web-app
    version: ~1.0.0
    repository: oci://fsflo.azurecr.io/helm
    condition: internal-web-app.enabled

  - name: pdf-generation-service
    version: ~1.0.0
    repository: oci://fsflo.azurecr.io/helm
    condition: pdf-generation-service.enabled

  - name: rabbitmq
    version: 12.1.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: global.rabbitmq.enabled
