SELECT U.UID, 
U.NAME, 
U.MAIL, 
R.NAME AS ROLE_TYPE_NAME, 
USERFIRSTNAME.FIELD_USER_FIRST_NAME_VALUE, 
USERLASTNAME.FIELD_USER_LAST_NAME_VALUE, 
USERADDRESS.FIELD_USER_ADDRESS_THOROUGHFARE, 
USERADDRESS.FIELD_USER_ADDRESS_PREMISE, 
USERADDRESS.FIELD_USER_ADDRESS_LOCALITY, 
USERADDRESS.FIELD_USER_ADDRESS_ADMINISTRATIVE_AREA, 
USERADDRESS.FIELD_USER_ADDRESS_COUNTRY, 
USERADDRESS.FIELD_USER_ADDRESS_POSTAL_CODE, 
USERADDRESS.FIELD_USER_ADDRESS_ORGANISATION_NAME, 
TELNO.FIELD_TELEPHONE_NUMBER_VALUE, 
MOBNO.FIELD_MOBILE_NUMBER_VALUE, 
USERCOMPANY.FIELD_COMPANY_NAME_VALUE 
FROM USERS U 
JOIN USERS_ROLES UR ON UR.UID = U.UID 
JOIN ROLE R ON R.RID = UR.RID 
LEFT OUTER JOIN FIELD_DATA_FIELD_USER_ADDRESS USERADDRESS ON U.UID = USERADDRESS.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_TELEPHONE_NUMBER TELNO ON U.UID = TELNO.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MOBILE_NUMBER MOBNO ON U.UID = MOBNO.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_USER_FIRST_NAME USERFIRSTNAME ON U.UID = USERFIRSTNAME.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_USER_LAST_NAME USERLASTNAME ON U.UID = USERLASTNAME.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_COMPANY_NAME USERCOMPANY ON U.UID = USERCOMPANY.ENTITY_ID 
WHERE U.STATUS = 1 
AND R.NAME IN ('agent','owner','FC Internal Agent')