SELECT NODE.NID AS MANAGED_OWNER_ID, 
	SELF_MO.FIELD_MANOW_SELF_MANAGED_OWNER_VALUE AS IS_SELF_MANAGED_OWNER, 
	MAN_FIRST.FIELD_MANOW_FIRST_NAME_VALUE, 
	MAN_LAST.FIELD_MANOW_LAST_NAME_VALUE, 
	MANEMAIL.FIELD_MANOW_EMAIL_ADDRESS_VALUE, 
	MANCOMP.FIELD_MANOW_COMPANY_VALUE, 
	MANTELE.FIELD_MANOW_TELEPHONE_VALUE AS TELNO, 
	MANMOBNO.FIELD_MOBILE_NUMBER_VALUE AS MOBNO, 
	MANADD.FIELD_MANOW_ADDRESS_THOROUGHFARE AS MANOW_ADD1, 
	MANADD.FIELD_MANOW_ADDRESS_PREMISE AS MANOW_ADD2, 
	MANADD.FIELD_MANOW_ADDRESS_LOCALITY AS MANOW_ADD3, 
	MANADD.FIELD_MANOW_ADDRESS_ADMINISTRATIVE_AREA AS MANOW_ADD4, 
	MANADD.FIELD_MANOW_ADDRESS_COUNTRY AS MANOW_ADD5, 
	MANADD.FIELD_MANOW_ADDRESS_POSTAL_CODE AS MANOW_POSTCODE, 
	MANADD.FIELD_MANOW_ADDRESS_ORGANISATION_NAME, 
	U.UID AS AGENT_USER_ID, 
	R.NAME AS AGENT_ROLE_TYPE_NAME 
FROM NODE 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_TELEPHONE MANTELE ON NODE.NID = MANTELE.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MOBILE_NUMBER MANMOBNO ON NODE.NID = MANMOBNO.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_ADDRESS MANADD ON NODE.NID = MANADD.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_EMAIL_ADDRESS MANEMAIL ON NODE.NID = MANEMAIL.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_FIRST_NAME MAN_FIRST ON NODE.NID = MAN_FIRST.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_LAST_NAME MAN_LAST ON NODE.NID = MAN_LAST.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_COMPANY MANCOMP ON NODE.NID = MANCOMP.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_AGENT MANAGENT ON NODE.NID = MANAGENT.ENTITY_ID 
LEFT OUTER JOIN FIELD_DATA_FIELD_MANOW_SELF_MANAGED_OWNER SELF_MO ON NODE.NID = SELF_MO.ENTITY_ID 
LEFT OUTER JOIN USERS U ON U.UID = MANAGENT.FIELD_MANOW_AGENT_TARGET_ID 
LEFT JOIN USERS_ROLES UR ON UR.UID = U.UID 
LEFT JOIN ROLE R ON R.RID = UR.RID 
WHERE NODE.TYPE = 'managed_owner'