apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-issuer
spec:
  acme:
    email: platform@qxlva.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ISRG Root X1
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: accounts@qxlva.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token